---
abstract: 'Verify that all changes and addition to the Perl files pass PerlCritic checks.'
author:
  - 'Guillaume Aubert <aubertg@cpan.org>'
build_requires:
  Capture::Tiny: '0'
  Git::Repository: '0'
  Test::Exception: '0'
  Test::FailWarnings: '0'
  Test::More: '0.94'
  Test::Requires::Git: '1.005'
  Test::Type: '0'
configure_requires:
  Module::Build: '0'
dynamic_config: 1
generated_by: 'Module::Build version 0.4205, CPAN::Meta::Converter version 2.140640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: App-GitHooks-Plugin-PerlCritic
provides:
  App::GitHooks::Plugin::PerlCritic:
    file: lib/App/GitHooks/Plugin/PerlCritic.pm
    version: v1.0.2
requires:
  App::GitHooks: '0'
  Perl::Critic: '0'
  Perl::Critic::Git: '0'
  Try::Tiny: '0'
  perl: '5.01'
resources:
  bugtracker: https://github.com/guillaumeaubert/App-GitHooks-Plugin-PerlCritic/issues
  homepage: https://metacpan.org/release/App-GitHooks-Plugin-PerlCritic
  license: http://dev.perl.org/licenses/
  repository: https://github.com/guillaumeaubert/App-GitHooks-Plugin-PerlCritic
version: v1.0.2
